'use client';

import AOS from "aos";
import "aos/dist/aos.css";
import { Poppins } from "next/font/google";
import { useEffect } from "react";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-geometric",
});

// export const metadata = {
//   title: "CherifAI",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  useEffect(() => {
    AOS.init({
      duration: 1500,   // animation duration in ms
      once: true,       // whether animation should happen only once
      easing: "ease-out-cubic",
      offset: 200,      // offset (in px) from the original trigger point
    });
  }, []);


  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
